# ##########################################################################
# File: Dockerfile.dev
# Author: Vatsal Gupta(gvatsal60)
# Date: 21-Sep-2025
# Description: Dockerfile for setting up a development environment
#              with Python 3.12, uv and necessary tools.
# ##########################################################################

# ##########################################################################
# License
# ##########################################################################
# This Dockerfile is licensed under the Apache 2.0 License.
# License information should be updated as necessary.
# ##########################################################################

# ##########################################################################
# Base Image
# ##########################################################################
FROM mcr.microsoft.com/devcontainers/python:3.12 AS base

# ##########################################################################
# Maintainer
# ##########################################################################
LABEL maintainer="Vatsal Gupta(gvatsal60)"

# ##########################################################################
# Environment Variables
# ##########################################################################
# Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive
# Disabled Telemetry
ENV ANONYMIZED_TELEMETRY=False
# Set the `uv` link mode to copy
ENV UV_LINK_MODE=copy

# ##########################################################################
# Install Dependencies
# ##########################################################################
# Update `pip`
RUN pip install --upgrade pip uv

# Install dependencies
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - \
  && apt-get update \
  && apt-get install -y nodejs

# Cleanup
RUN rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

# ##########################################################################
# Expose Port
# ##########################################################################
EXPOSE 8501

# ##########################################################################
# Command to Run
# ##########################################################################
