name: Sync to Hugging Face hub
on:
  push:
    branches: ["master"]
permissions:
  contents: write
  pull-requests: write
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ github.repository_owner }}
          HF_SPACE: ${{ github.repository }}
          HF_BRANCH: main
        run: |
          git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_SPACE $HF_BRANCH
