name: Sync to Hugging Face hub
on:
  push:
    branches: ["master"]
permissions:
  contents: write
  pull-requests: write
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    environment: HF_TOKEN
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          lfs: true
      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "${{ github.actor }}"
      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ github.repository_owner }}
          HF_SPACE: ${{ github.repository }}
          HF_BRANCH: main
        run: |
          git remote set-url origin https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_SPACE
          git push origin master:$HF_BRANCH
