name: Test on Hugging Face hub
on:
  pull_request:
    branches: ["*"]
permissions:
  contents: write
  pull-requests: write
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    environment: HF_TOKEN
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          lfs: true
      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"
      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ github.repository_owner }}
          HF_SPACE: ${{ github.repository_owner }}/github-test
          HF_BRANCH: main
          PR_BRANCH: ${{ github.head_ref }}
        run: |
          git remote set-url origin https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_SPACE
          git push origin $PR_BRANCH:$HF_BRANCH --force
